apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-shop
spec:
  replicas: 6
  selector:
    matchLabels:
      app: fake-shop
  template:
    metadata:
      labels:
        app: fake-shop
    spec:  
      containers:
      - name: fake-shop
        image: clar1703/fake-shop:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: fake-shop
spec:
  selector: 
    app: fake-shop
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31000
  type: NodePort