name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter codigo do projeto
        run: actions.checkout@v4
      - name: Autenticar no dockerhub - Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Autenticar no Docker Hub
        run: echo "Exceutando o comando docker login"
      - name: Construcao da imagem docker
        run: echo "Executando comando docker build"
      - name: Envio da imagem docker
        run: echo "Executando o comando docker push..."
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Autenticar aws
        run: echo "Exceutando o comando aws"
      - name: Construcao da imagem docker
        run: echo "Executando comando docker build"
      - name: Envio da imagem docker
        run: echo "Executando o comando docker push..."

    
  